### ISSUE TITLE
Setup auto-publish for website

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs102#6]
Would be cool.

**Comment by twentylemon** [comment]
https://github.com/golfzaptw/action-connect-ovpn
https://stackoverflow.com/questions/63354866/how-to-execute-command-from-github-action-via-ssh-into-whitelisted-server

https://github.com/appleboy/ssh-action

**Comment by jameshughes89** [comment]
Currently have a ticket open to get the stuff I need.

**Comment by jameshughes89** [comment]
Maybe I can SSH into my little guy and then copy it over.

**Comment by jameshughes89** [comment]
Or this
https://aws.amazon.com/s3/pricing/?nc=sn&loc=4

**Comment by twentylemon** [comment]
If you're going down the aws/s3 route, it may be worth publishing to a personal website as opposed to csci162.com (eg `jhughes.ca/csci162`). It'd allow you do the setup once, then the actions would write to `bucket/repo`.

Alternatively, you could invest into [cloudformation](https://aws.amazon.com/cloudformation/), which is essentially a yml template you deploy which creates aws resources for you, like the s3 bucket, IAM roles, etc etc, that you would otherwise manually set up. The template could live in this repo (a [linter](https://github.com/aws-cloudformation/cfn-lint) might be useful). Using cloudformation, you could have several sets of parallel tracks for websites/courses instead of a single one.

That said, there's no reason you can't combine the two. You could have a main cloudformation stack for the s3 bucket and single website, then per-course stacks for IAM roles and course specific things.
